### ISSUE TITLE
remapping of task variable names

### ISSUE THREAD

**Issue by mharms** [ABCD-STUDY/analysis-nda17#1]
Hi,
Any estimate of when the variables from the task fMRI instruments will be added into 'alias_mapping.csv', to improve the consistency and readability of the task fMRI data?

thanks,
-Mike H.

**Comment by HaukeBartsch** [comment]
We have started with the free surfer aliases. That should be done in the next couple of days. We will followup with the DTI/RSI measures and afterwards the new names of the task fMRI instruments.

**Comment by HaukeBartsch** [comment]
The new alias files are now available. They are separately containing the new alias names for free surfer, DTI and resting state scans.
