### ISSUE TITLE
highest.household.income is missing 

### ISSUE THREAD

**Issue by stealthybif** [ABCD-STUDY/analysis-nda17#3]
In the [impute missing demographics notes](https://github.com/ABCD-STUDY/analysis-nda17/blob/master/notebooks/general/impute_demographics.md), a variable 'highest.household.income' is referred to. However it is not created in the [recode core demographics section](https://github.com/ABCD-STUDY/analysis-nda17/blob/master/notebooks/derived/core_demographic.md). 

Wondering if it is a typo and just 'household.income' is needed or if the calculation for 'highest.household.income' is missing from the recode script

**Comment by jkuperma** [comment]
Hi Eric,

I (Hauke) will need to update the document. The variable is calculated - its just that the name has beeb changed recently. Can you put an issue into the project on github? The variable name should be “household.income”.

Thanks for noticing!
   Hauke & Josh

**Comment by HaukeBartsch** [comment]
That is a typo, the correct name is household.income (sum of all the income of the parents/guardians in the household).
