### ISSUE TITLE
Pre-generated Package ABCD-RELEASE-1

### ISSUE THREAD

**Issue by utooley** [ABCD-STUDY/analysis-nda17#5]
In the readme, it says that "The data for this release can be downloaded from NDA using a pre-generated package "ABCD-RELEASE-1" using the Download Manager tool provided by NDA."

I am not able to find a pre-generated package called ABCD-RELEASE-1 on the Download Manager--who should I contact regarding this?

**Comment by HaukeBartsch** [comment]
You should have access to the package once you have access to the ABCD release on NDA. Check if that is the case.

The generation and distribution of these packages is done by NDA. You can send a message to the NDA helpdesk and they can make the package available to you. We are releasing 1.1 very soon, you might also want to wait for the updated package for the new release.

**Comment by HaukeBartsch** [comment]
There will be changes to the scripts. Mostly variables names that are different now. You can see the changes if you switch to the release-1.1 version of the scripts.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/603956/47597160-2dd78200-d941-11e8-8857-240e3f52d8c1.png">

**Comment by utooley** [comment]
Thanks, that's incredibly helpful!
